[package]
name = "fast_arrays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.test]
# uncomment to get maximum performance when testing
# opt-level = 3
# debug = 0

[dependencies]
